"""Users relation

Revision ID: 68cb1cf9c0ba
Revises:
Create Date: 2026-06-14 13:50:15.288171

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68cb1cf9c0ba"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "users",
        sa.Column("id", sa.String, index=True, primary_key=True),
        sa.Column("email", sa.String),
        sa.Column("role", sa.String),
        sa.Column("name", sa.String, nullable=True),
        sa.Column("surname", sa.String, nullable=True),
        sa.Column("password", sa.String),
        sa.Column("is_active", sa.Boolean, default=False),
        sa.Column("created_at", sa.DateTime(timezone=True)),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
